<a href="https://colab.research.google.com/github/ThanikPimpiban/DWDM21/blob/main/Project_31_8_64.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import os

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
path = '/content/drive/My Drive/DWDM_Project'

In [54]:
data_st = pd.read_csv(os.path.join(path,'data_station.csv'))
data_st

      id  station_code           name  ... giveway dual_track          comment
0      1          1001        กรุงเทพ  ...       1          1              NaN
1      2          1002          ยมราช  ...       1          1              NaN
2      3          1004         สามเสน  ...       1          1              NaN
3      4          1006     ประดิพัทธ์  ...       1          1          ป.สระอิ
4      5          1007  ชุมทางบางซื่อ  ...       1          1              NaN
..   ...           ...            ...  ...     ...        ...              ...
677  678          5025       บางโทรัด  ...       0          0  ศก.สน. กม.13.82
678  679          5026      บ้านกาหลง  ...       0          0  ศก.สน. กม.15.78
679  680          5027     บ้านนาขวาง  ...       0          0  ศก.สน. กม.17.94
680  681          5028      บ้านนาโคก  ...       0          0  ศก.สน. กม.19.97
681  682          5029       เขตเมือง  ...       0          0  ศก.สน. กม.23.73

[682 rows x 18 columns]

In [55]:
data_t = pd.read_csv(os.path.join(path,'data_train.csv'))
data_t.dropna()

     Zone  goback   Num  ...            NameStEng            NameStEng_L  Service
0       1       1   0.0  ...              Bangkok       Ban Plu Ta Luang    False
1       1       1   1.0  ...              Bangkok      Bang Sue Junction     True
2       1       1   1.0  ...             Makkasan              Hua Takhe    False
3       1       1   2.0  ...              Bangkok      Bang Sue Junction     True
4       1       1   4.0  ...              Bangkok       Ban Plu Ta Luang    False
..    ...     ...   ...  ...                  ...                    ...      ...
229     5       2  26.0  ...              Nam Tok              Thon Buri    False
230     5       2  27.0  ...  Prachuap Khiri Khan              Thon Buri    False
231     5       2  28.0  ...            Lang Suan              Thon Buri    False
232     5       2  29.0  ...              Nam Tok              Thon Buri    False
233     5       2  30.0  ...              Nam Tok  Nong Pla Duk Junction    False

[234 rows x 12 columns]

In [56]:
data_rst = pd.read_csv(os.path.join(path,'railstation.csv'))
data_rst.dropna()

     OBJECTID                              NAMET  ...          Y Neareat_AH
0           1            ที่หยุดรถไฟบ้านเกาะปริง  ...   8.213274
1           2                   สถานีรถไฟห้วยยอด  ...   7.785456
2           3   ที่หยุดรถไฟโรงเรียนการบิน (ขึ้น)  ...  14.088246
3           4             ที่หยุดรถไฟบ้านปลักแรด  ...  14.530267
4           5                   สถานีรถไฟเด่นชัย  ...  17.980781       AH13
..        ...                                ...  ...        ...        ...
677       678  ที่หยุดรถไฟศูนย์ราชการจังหวัดสระแ  ...  13.799641
678       679                 ที่หยุดรถไฟทุ่งทอง  ...  13.980168
679       680             ที่หยุดรถไฟตลาดหนองคาย  ...  17.878784
680       681            ที่หยุดรถไฟแกรนด์ คาแนล  ...  13.941516
681       682        สถานีรถไฟกรุงเทพ (หัวลำโพง)  ...  13.744026        AH2

[682 rows x 9 columns]

In [68]:
merged_data_st_data_rst = data_st.merge(data_rst,how='left',left_on='id',right_on='OBJECTID')
merged_data_st_data_rst

      id  station_code           name  ...           X          Y Neareat_AH
0      1          1001        กรุงเทพ  ...   99.644994   8.213274
1      2          1002          ยมราช  ...   99.637987   7.785456
2      3          1004         สามเสน  ...   99.956660  14.088246
3      4          1006     ประดิพัทธ์  ...  100.725785  14.530267
4      5          1007  ชุมทางบางซื่อ  ...  100.046225  17.980781       AH13
..   ...           ...            ...  ...         ...        ...        ...
677  678          5025       บางโทรัด  ...  102.138802  13.799641
678  679          5026      บ้านกาหลง  ...   99.638000  13.980168
679  680          5027     บ้านนาขวาง  ...  102.725416  17.878784
680  681          5028      บ้านนาโคก  ...  100.608267  13.941516
681  682          5029       เขตเมือง  ...  100.516732  13.744026        AH2

[682 rows x 27 columns]

In [79]:
merged_3_tables =data_t.merge(merged_data_st_data_rst,how='right',left_on='StStart',right_on='station_code')
merged_3_tables

     Zone  goback  Num  IdTrain  ...      TamName           X          Y  Neareat_AH
0     1.0     1.0  0.0    997.0  ...                99.644994   8.213274
1     1.0     1.0  1.0   1049.0  ...                99.644994   8.213274
2     1.0     1.0  2.0   1053.0  ...                99.644994   8.213274
3     1.0     1.0  4.0    283.0  ...                99.644994   8.213274
4     1.0     1.0  5.0    285.0  ...                99.644994   8.213274
..    ...     ...  ...      ...  ...          ...         ...        ...         ...
855   NaN     NaN  NaN      NaN  ...               102.138802  13.799641
856   NaN     NaN  NaN      NaN  ...                99.638000  13.980168
857   NaN     NaN  NaN      NaN  ...               102.725416  17.878784
858   NaN     NaN  NaN      NaN  ...               100.608267  13.941516
859   NaN     NaN  NaN      NaN  ...  RONG MUEANG  100.516732  13.744026         AH2

[860 rows x 39 columns]

## ลองวิเคราะห์

In [94]:
Ex_0 = merged_3_tables[merged_3_tables['class']==98]
Ex_0[['name','class']]

            name  class
82   ทุ่งสองห้อง     98
87    คลองรังสิต     98
90         นวนคร     98
103  บ้านปลักแรด     98
120      ไผ่ใหญ่     98
..           ...    ...
854      บ้านบ่อ     98
855     บางโทรัด     98
856    บ้านกาหลง     98
857   บ้านนาขวาง     98
858    บ้านนาโคก     98

[178 rows x 2 columns]

In [95]:
Ex_1 = merged_3_tables.sort_values(by=['station_code'],ascending=False)
Ex_1[['station_code','name','comment']]

     station_code        name          comment
859          5029    เขตเมือง  ศก.สน. กม.23.73
858          5028   บ้านนาโคก  ศก.สน. กม.19.97
857          5027  บ้านนาขวาง  ศก.สน. กม.17.94
856          5026   บ้านกาหลง  ศก.สน. กม.15.78
855          5025    บางโทรัด  ศก.สน. กม.13.82
..            ...         ...              ...
52           1001     กรุงเทพ              NaN
53           1001     กรุงเทพ              NaN
54           1001     กรุงเทพ              NaN
55           1001     กรุงเทพ              NaN
0            1001     กรุงเทพ              NaN

[860 rows x 3 columns]